# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebooklog', '0005_auto_20170608_1215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='afam',
        ),
    ]
