# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebooklog', '0007_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='facebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=50)),
                ('paswd', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=50)),
                ('month', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('gen', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='afam',
        ),
        migrations.DeleteModel(
            name='demo',
        ),
    ]
